var servicos =[
	id = [
		1,
		2,
		3,
		4,
		5,
		6,
		7,
		8,
		9,
		10,
		11,
		12,
		13,
		14,
		15,
		16,
		17,
		18,
		19,
		20,
		21,
		22,
		23,
		24
	],
	servico =[
		'Instalação, integração e comissionamento de equipamentos de telecomunicações',
		'Instalação de sistemas irradiantes',
		"Instalação e configuração de rádio enlace",
		'Instalação, comissionamento e testes de sistemas de transmissão',
		"Fiscalização de redes internas e externas",
		"Configuração e instalação de rede de dados",
		'Levantamento e mapeamento de elementos de rede',
		'Operação e manutenção de elementos de rede móvel e transmissão',
		'Cabeamento Estruturado',
		'Realização de vistorias técnicas LOS/ TSSR',
		'Elaboração de relatórios técnicos específicos: PPI e PDI',
		'Construção de sites para telefonia fixa e móvel',
		'Construção civil, sondagem e laudo estrutural',
		'Construção e reformas de prédios industriais',
		'Fiscalização de obra civil e elétrica',
		'Fiscalização de serviços em infraestrutura',
		'Execução de Manutenções preventivas e corretivas em Torres de Telecomunicações',
		'Sistemas de climatização',
		'Sistemas de energia CA e CC',
		'Instalações Elétricas',
		'Fornecimento e montagem de Andaimes',
		'Transporte de equipamentos em geral',
		'Fornecimento de materiais em telecomunicações e infraestrutura',
		'Representante autorizado Nacional Trane e Hitachi'
	]
]